# Generated by Django 4.2.30 on 2026-07-09 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=100)),
                ('origin_iata', models.CharField(blank=True, max_length=3, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_budget', models.PositiveIntegerField()),
                ('adult', models.PositiveIntegerField()),
                ('kid', models.PositiveIntegerField(default=0)),
                ('themes', models.JSONField(blank=True, null=True)),
                ('raw_input', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_order', models.PositiveIntegerField()),
                ('city_name', models.CharField(max_length=100)),
                ('city_en', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('iata_code', models.CharField(blank=True, max_length=3, null=True)),
                ('nights', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='trips.triprequest')),
            ],
            options={
                'ordering': ['seq_order'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=36)),
                ('role', models.CharField(choices=[('user', '사용자'), ('ai', 'AI')], max_length=10)),
                ('content', models.TextField()),
                ('param_diff', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='trips.triprequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='tripdestination',
            constraint=models.UniqueConstraint(fields=('request', 'seq_order'), name='uniq_destination_order_per_request'),
        ),
    ]
