# Generated by Django 4.2.30 on 2026-07-09 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tripdestination',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processing', '생성 중'), ('draft', '임시'), ('confirmed', '확정')], default='processing', max_length=12)),
                ('allocation', models.JSONField(blank=True, null=True)),
                ('narrative', models.TextField(blank=True, null=True)),
                ('edit_request', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='trips.triprequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liteapi_hotel_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('stars', models.PositiveIntegerField(blank=True, null=True)),
                ('price_krw', models.PositiveIntegerField()),
                ('price_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('utility', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('utility_reasons', models.JSONField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='trips.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=100)),
                ('airline', models.CharField(max_length=100)),
                ('price_krw', models.PositiveIntegerField()),
                ('price_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('utility', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('utility_reasons', models.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('slices', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='trips.plan')),
            ],
        ),
    ]
