# Generated by Django 4.2.30 on 2026-07-09 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_chatmessage_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trips.plan')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_order', models.PositiveIntegerField()),
                ('place_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('place_detail', models.JSONField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('duration_min', models.PositiveIntegerField(blank=True, null=True)),
                ('est_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('travel_min_to_next', models.PositiveIntegerField(blank=True, null=True)),
                ('travel_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trips.itineraryday')),
            ],
            options={
                'ordering': ['visit_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='itineraryitem',
            constraint=models.UniqueConstraint(fields=('day', 'visit_order'), name='uniq_visit_order_per_day'),
        ),
        migrations.AddConstraint(
            model_name='itineraryday',
            constraint=models.UniqueConstraint(fields=('plan', 'day_number'), name='uniq_day_number_per_plan'),
        ),
    ]
